### ISSUE TITLE
Doesn't seem to get click event

### ISSUE THREAD

**Issue by bfourgeaud** [VinceG/vue-click-away#11]
It seems that only the **TouchEvents** are recorded and not the **ClickEvents**.  
I don't know if it is a bug or the default behaviour.  

In fact my config :  

```js
<script setup>
  import { directive as ClickAway } from 'vue3-click-away'

  function onClickAway(event) {
    console.log(event)
  }
</script>
```

```vue
<div v-click-away="onClickAway">
...
</div>
```

When I inspect in **Desktop mode nothing is outputted** in the console when i click outside.  
When I inspect in **Mobile view I get TouchEvent {...}** logged out every time i touch outside the div.  

## Package.json
```json
"dependencies": {
    "axios": "^0.21.1",
    "vue": "^3.0.5",
    "vue-router": "^4.0.6",
    "vue3-click-away": "^1.2.1",
    "vuex": "^4.0.0"
  },
```

Thank you for your work on this vue3 module, because It helps a lot !  

# UPDATE
If you remove the param in onClickAway method it works.
I got that from the vue-clickaway repo (https://github.com/simplesmiler/vue-clickaway) 

> Prior to vue@^2.0, directive were able to accept statements. This is no longer the case. If you need to pass arguments, just do v-on-clickaway="() => away(arg1)".

**Comment by VinceG** [comment]
@bfourgeaud hmm that's interesting, the callback does accept the event this is where its being passed:
https://github.com/VinceG/vue-click-away/blob/master/index.js#L23

i am glad you got it working.

**Comment by bfourgeaud** [comment]
It is related to vue3 directives
