### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by StarkShang** [VinceG/vue-click-away#12]
Hi, @VinceG , thanks for your works.
Could you add typescript type defines for vue-click-away?

**Comment by VinceG** [comment]
@StarkShang is this what you need? 
https://github.com/VinceG/vue-click-away/blob/master/types/index.d.ts

if not can you help and submit a PR for the additional types

**Comment by StarkShang** [comment]
Yes, that is what exactly I want! Thanks.
