### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by revenkroz** [VinceG/vue-click-away#18]
[The first string](https://github.com/VinceG/vue-click-away/blob/97145ee255f429f87142723c830979ab9d454b99/index.js#L1) is being executed immediately (on script load) and it throws and error on SSR mode:
```
ReferenceError: document is not defined
```

**Comment by toniengelhardt** [comment]
I have a similar problem in Nuxt 3. Every element that has the v-click-away directive needs to be wrapped in a `<ClientOnly>` tag, otherwise it breaks on SSR. The directive should probably check if window/document is available.
